# if necessary not you could automate getting all endpoints from the main page
# since we have code working for a hardcoded list of endpoints
urls = [
    # 'https://api.raporty.pse.pl/api/ogr-oper',
    # 'https://api.raporty.pse.pl/api/ogr-oper-head',
    # 'https://api.raporty.pse.pl/api/it-omb-rbb',
    # 'https://api.raporty.pse.pl/api/price-fcst',
    # 'https://api.raporty.pse.pl/api/price-cost',
    # 'https://api.raporty.pse.pl/api/pk5l-wp',
    # 'https://api.raporty.pse.pl/api/unav-pk5l',
    # 'https://api.raporty.pse.pl/api/pdgopkd',
    # 'https://api.raporty.pse.pl/api/pdgobpkd',
    # 'https://api.raporty.pse.pl/api/ogr-d1',
    # 'https://api.raporty.pse.pl/api/ogr-d1-head',
    # 'https://api.raporty.pse.pl/api/ogr-d2',
    # 'https://api.raporty.pse.pl/api/ogr-d2-head',
    # 'https://api.raporty.pse.pl/api/ogr-d39',
    # 'https://api.raporty.pse.pl/api/ogr-d39-head',
    # 'https://api.raporty.pse.pl/api/ogr-m',
    # 'https://api.raporty.pse.pl/api/ogr-m-head',
    # 'https://api.raporty.pse.pl/api/ogr-r',
    # 'https://api.raporty.pse.pl/api/ogr-r-head',
    # 'https://api.raporty.pse.pl/api/poze-redoze',
    # 'https://api.raporty.pse.pl/api/rcco2',
    # 'https://api.raporty.pse.pl/api/crb-rozl',
    # 'https://api.raporty.pse.pl/api/krb-rozl',
    # 'https://api.raporty.pse.pl/api/kmb-kro-rozl',
    # 'https://api.raporty.pse.pl/api/rce-pln',
    # 'https://api.raporty.pse.pl/api/cordmax',
    # 'https://api.raporty.pse.pl/api/cmbp-tp',
    # 'https://api.raporty.pse.pl/api/csdac-pln',
    # 'https://api.raporty.pse.pl/api/cmbu-tu',
    # 'https://api.raporty.pse.pl/api/it-oeb-rbb',
    # 'https://api.raporty.pse.pl/api/it-pp-rbb',
    # 'https://api.raporty.pse.pl/api/it-use-rbb',
    # 'https://api.raporty.pse.pl/api/ro-rozl',
    # 'https://api.raporty.pse.pl/api/ro-prog',
    # 'https://api.raporty.pse.pl/api/mbu-tu',
    # 'https://api.raporty.pse.pl/api/mbp-tp',
    # 'https://api.raporty.pse.pl/api/eb-rozl',
    # 'https://api.raporty.pse.pl/api/zmb',
    # 'https://api.raporty.pse.pl/api/en-rozl',
    # 'https://api.raporty.pse.pl/api/zeb-rozl',
    # 'https://api.raporty.pse.pl/api/ogr-rmb',
    # 'https://api.raporty.pse.pl/api/oeb-bpkdbo',
    # 'https://api.raporty.pse.pl/api/pomb-rbn',
    # 'https://api.raporty.pse.pl/api/popmb-rmb',
    # 'https://api.raporty.pse.pl/api/use-sprz-rbb',
    # 'https://api.raporty.pse.pl/api/use-sprz-rbn',
    # 'https://api.raporty.pse.pl/api/wsp-wrm',
    # 'https://api.raporty.pse.pl/api/cor',
    # 'https://api.raporty.pse.pl/api/pdwkseub',
    # 'https://api.raporty.pse.pl/api/przeplywy-mocy',
    # 'https://api.raporty.pse.pl/api/sk',
    'https://api.raporty.pse.pl/api/energy-prices',
    # 'https://api.raporty.pse.pl/api/his-wlk-cal',
    # 'https://api.raporty.pse.pl/api/his-bil-mocy',
    # 'https://api.raporty.pse.pl/api/kse-load',
    # 'https://api.raporty.pse.pl/api/gen-jw',
    # 'https://api.raporty.pse.pl/api/it-opmb-rmb',
    # 'https://api.raporty.pse.pl/api/it-use-rbn',
    'https://api.raporty.pse.pl/api/it-ot-rbn',
    # 'https://api.raporty.pse.pl/api/it-oeb-rbn',
    # 'https://api.raporty.pse.pl/api/it-pp-rbn',
    # 'https://api.raporty.pse.pl/api/it-omb-rbn',
    # 'https://api.raporty.pse.pl/api/cor-q-1',
    # 'https://api.raporty.pse.pl/api/codn',
    'https://api.raporty.pse.pl/api/lolp',
    'https://api.raporty.pse.pl/api/specwezlow',
    # 'https://api.raporty.pse.pl/api/his-gen-pal',
    # 'https://api.raporty.pse.pl/api/poeb-rbn',
    # 'https://api.raporty.pse.pl/api/poeb-rbb',
    # 'https://api.raporty.pse.pl/api/ogr-b',
    # 'https://api.raporty.pse.pl/api/ogr-b-head',
    # 'https://api.raporty.pse.pl/api/pdgsz'
    'https://api.raporty.pse.pl/api/ogr-oper-head',
    'https://api.raporty.pse.pl/api/unav-pk5l',
    'https://api.raporty.pse.pl/api/ogr-d1-head',
    'https://api.raporty.pse.pl/api/ogr-d2-head',
    'https://api.raporty.pse.pl/api/ogr-d39-head',
    'https://api.raporty.pse.pl/api/ogr-m',
    'https://api.raporty.pse.pl/api/ogr-m-head',
    'https://api.raporty.pse.pl/api/ogr-r-head',
    'https://api.raporty.pse.pl/api/rcco2',
    'https://api.raporty.pse.pl/api/cordmax',
    'https://api.raporty.pse.pl/api/his-bil-mocy',
    'https://api.raporty.pse.pl/api/it-opmb-rmb',
    'https://api.raporty.pse.pl/api/it-use-rbn',
    'https://api.raporty.pse.pl/api/it-ot-rbn',
    'https://api.raporty.pse.pl/api/it-oeb-rbn',
    'https://api.raporty.pse.pl/api/it-pp-rbn',
    'https://api.raporty.pse.pl/api/it-omb-rbn',
    'https://api.raporty.pse.pl/api/cor-q-1',
    'https://api.raporty.pse.pl/api/codn',
    'https://api.raporty.pse.pl/api/ogr-b-head'
]
